sport_data_solution:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: sport_silver
      threads: 4
      timeout_seconds: 300
      location: europe-west1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"